version: '3.8'

services:
  express:
    build: .
    container_name: express-app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
    networks:
      - app-network
    volumes:
      - ./dist:/app/dist

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - express
    networks:
      - app-network
    volumes:
      - ./dist:/usr/share/nginx/html

networks:
  app-network:
    driver: bridge

volumes:
  static-files: