version: '3.8'

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile.express
    container_name: express-app
    ports:
      - "8000:8000"  # Expose port 8000 for internal communication
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    volumes:
      - static-files:/app/public  # 공유 볼륨 설정

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx-proxy
    ports:
      - "80:80"  # Expose port 80 for external access
    depends_on:
      - express
    networks:
      - app-network
    volumes:
      - static-files:/usr/share/nginx/html  # NGINX에서 같은 볼륨을 참조

networks:
  app-network:
    driver: bridge

volumes:
  static-files:
